import { HolidayDestinationType } from "../models/holidayDestination.model";

export const testHolidayData: HolidayDestinationType[] =  [
    {
        "holidayReference": 1,
        "hotelName": "Uptown",
        "city": "Bali",
        "continent": "Asia",
        "country": "Indonesia",
        "category": "active",
        "starRating": 3,
        "tempRating": "mild",
        "location": "mountain",
        "pricePerPerNight": 120
    },
    {
        "holidayReference": 2,
        "hotelName": "Relaxamax",
        "city": "New Orleans",
        "continent": "North America",
        "country": "USA",
        "category": "lazy",
        "starRating": 4,
        "tempRating": "mild",
        "location": "city",
        "pricePerPerNight": 28
    },
    {
        "holidayReference": 3,
        "hotelName": "WindyBeach",
        "city": "Ventry",
        "continent": "Europe",
        "country": "Ireland",
        "category": "active",
        "starRating": 3,
        "tempRating": "mild",
        "location": "sea",
        "pricePerPerNight": 42
    },
    {
        "holidayReference": 4,
        "hotelName": "Twighlight",
        "city": "Marrakech",
        "continent": "Africa",
        "country": "Morocco",
        "category": "lazy",
        "starRating": 5,
        "tempRating": "cold",
        "location": "mountain",
        "pricePerPerNight": 50
    },
    {
        "holidayReference": 5,
        "hotelName": "TooHot",
        "city": "Sydney",
        "continent": "Australia",
        "country": "Australia",
        "category": "lazy",
        "starRating": 5,
        "tempRating": "hot",
        "location": "sea",
        "pricePerPerNight": 67
    },
    {
        "holidayReference": 6,
        "hotelName": "Castaway",
        "city": "",
        "continent": "Africa",
        "country": "The Maldives",
        "category": "lazy",
        "starRating": 3,
        "tempRating": "mild",
        "location": "sea",
        "pricePerPerNight": 120
    },
    {
        "holidayReference": 7,
        "hotelName": "Eiffel Park",
        "city": "Paris",
        "continent": "Europe",
        "country": "France",
        "category": "active",
        "starRating": 4,
        "tempRating": "mild",
        "location": "city",
        "pricePerPerNight": 45
    },
    {
        "holidayReference": 8,
        "hotelName": "The Cape",
        "city": "Cape Town",
        "continent": "Africa",
        "country": "South Africa",
        "category": "active",
        "starRating": 4,
        "tempRating": "mild",
        "location": "sea",
        "pricePerPerNight": 78
    },
    {
        "holidayReference": 9,
        "hotelName": "Desert Dreams",
        "city": "Dubai",
        "continent": "Asia",
        "country": "U.A.E",
        "category": "active",
        "starRating": 4,
        "tempRating": "hot",
        "location": "mountain",
        "pricePerPerNight": 67
    },
    {
        "holidayReference": 10,
        "hotelName": "SeaViews",
        "city": "Bora Bora",
        "continent": "Australia",
        "country": "French Polynesia",
        "category": "active",
        "starRating": 3,
        "tempRating": "mild",
        "location": "sea",
        "pricePerPerNight": 54
    },
    {
        "holidayReference": 11,
        "hotelName": "AppleCity",
        "city": "New York",
        "continent": "North America",
        "country": "USA",
        "category": "active",
        "starRating": 3,
        "tempRating": "mild",
        "location": "city",
        "pricePerPerNight": 27
    },
    {
        "holidayReference": 12,
        "hotelName": "IslandHopper",
        "city": "Dubrovnik",
        "continent": "Europe",
        "country": "Croatia",
        "category": "active",
        "starRating": 5,
        "tempRating": "mild",
        "location": "sea",
        "pricePerPerNight": 78
    },
    {
        "holidayReference": 13,
        "hotelName": "CastleTown",
        "city": "Edinburgh",
        "continent": "Europe",
        "country": "Scotland",
        "category": "lazy",
        "starRating": 3,
        "tempRating": "mild",
        "location": "city",
        "pricePerPerNight": 53
    },
    {
        "holidayReference": 14,
        "hotelName": "WineValley",
        "city": "Rome",
        "continent": "Europe",
        "country": "Italy",
        "category": "lazy",
        "starRating": 5,
        "tempRating": "mild",
        "location": "city",
        "pricePerPerNight": 25
    },
    {
        "holidayReference": 15,
        "hotelName": "WearyTraveller",
        "city": "Paro Valley",
        "continent": "Asia",
        "country": "Bhutan",
        "category": "active",
        "starRating": 5,
        "tempRating": "mild",
        "location": "mountain",
        "pricePerPerNight": 54
    },
    {
        "holidayReference": 16,
        "hotelName": "HotTimes",
        "city": "Jaipur",
        "continent": "Asia",
        "country": "India",
        "category": "lazy",
        "starRating": 4,
        "tempRating": "hot",
        "location": "sea",
        "pricePerPerNight": 67
    },
    {
        "holidayReference": 17,
        "hotelName": "ForestRetreat",
        "city": "Waikato",
        "continent": "Australia",
        "country": "New Zealand",
        "category": "active",
        "starRating": 4,
        "tempRating": "mild",
        "location": "mountain",
        "pricePerPerNight": 89
    },
    {
        "holidayReference": 18,
        "hotelName": "Casablanca",
        "city": "Havana",
        "continent": "North America",
        "country": "Cuba",
        "category": "lazy",
        "starRating": 5,
        "tempRating": "mild",
        "location": "city",
        "pricePerPerNight": 29
    },
    {
        "holidayReference": 19,
        "hotelName": "TechCity",
        "city": "Tokyo",
        "continent": "Asia",
        "country": "Japan",
        "category": "active",
        "starRating": 3,
        "tempRating": "mild",
        "location": "city",
        "pricePerPerNight": 71
    },
    {
        "holidayReference": 20,
        "hotelName": "IceHotel",
        "city": "Base Marambio",
        "continent": "Antarctica",
        "country": "Antartica",
        "category": "active",
        "starRating": 5,
        "tempRating": "cold",
        "location": "mountain",
        "pricePerPerNight": 270
    },
    {
        "holidayReference": 21,
        "hotelName": "NorthStar",
        "city": "",
        "continent": "Arctic",
        "country": "Greenland",
        "category": "active",
        "starRating": 5,
        "tempRating": "cold",
        "location": "mountain",
        "pricePerPerNight": 250
    }
]